---
name: Test-Pod-Snippets
version: 0.01
author:
  - 'Yanick Champoux <cpan@babyl.dyndns.org>'
abstract: Generate tests from pod code snippets
license: perl
build_requires:
  Pod::Parser: 0
  Test::More: 0
provides:
  Test::Pod::Snippets:
    file: lib/Test/Pod/Snippets.pm
    version: 0.01
generated_by: Module::Build version 0.2612
